version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for live reload in development
      - .:/app
      # Persist SQLite database
      - ./data:/app/data
      # Persist media files
      - ./media:/app/media
      # Persist logs
      - ./logs:/app/logs
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-dev-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DATABASE_PATH=data/db.sqlite3
    depends_on: []
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db_data:
  media_files:
  log_files: