services:
  - type: web
    name: django-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/db.sqlite3
    healthCheckPath: /