# Generated by Django 5.0.3 on 2025-09-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Image URL (alternative to file upload)",
                null=True,
            ),
        ),
    ]
